1. esense irregular time intervals (Nominal for 50Hz - 20 ms)
2.

In [163]:
import pandas as pd
df_sub2_esense = pd.read_csv('..\sensor_data\eSense_sbj2.csv', names=['time','Device','1','2','3','4','5','6','Label'], index_col=0)
df_sub2_esense.index = pd.to_datetime(df_sub2_esense.index, unit='ms') + pd.Timedelta('02:00:00')
#df_sub2_esense.index = pd.date_range(start=df_sub2_esense.index[0], periods = df_sub2_esense.shape[0], freq="20ms")
#df_sub2_esense = df_sub2_esense.resample('10ms', origin='start').first().interpolate()
df_sub2_esense.sort_index()

,Device,1,2,3,4,5,6,Label
time,,,,,,,,
2021-04-14 19:00:07.664,eSense-0540,-0.875000,-0.154053,0.011719,-7.835366,7.591463,-3.079268,shooting
2021-04-14 19:00:07.670,eSense-0540,-0.875244,-0.156738,0.005127,-7.865854,6.829268,-4.176829,shooting
2021-04-14 19:00:07.672,eSense-0540,-0.881348,-0.153320,0.004639,-9.298780,6.707317,-4.085366,shooting
2021-04-14 19:00:07.768,eSense-0540,-0.879639,-0.151123,0.001465,-10.335366,7.012195,-1.463415,shooting
2021-04-14 19:00:07.771,eSense-0540,-0.882324,-0.156006,0.000732,-12.134146,6.646341,-0.945122,shooting
...,...,...,...,...,...,...,...,...
2021-04-14 19:42:09.093,eSense-0540,-0.822510,0.235840,-0.650391,0.548780,4.847561,9.054878,NaN
2021-04-14 19:42:09.095,eSense-0540,-0.816895,0.234131,-0.634033,-7.103659,1.402439,4.054878,NaN
2021-04-14 19:42:09.097,eSense-0540,-0.827637,0.224854,-0.619141,1.371951,9.115854,-2.256098,NaN
2021-04-14 19:42:09.198,eSense-0540,-0.779297,0.263672,-0.598145,2.560976,6.737805,-7.042683,NaN
2021-04-14 19:42:09.200,eSense-0540,-0.738037,0.318115,-0.620117,-18.140244,2.896341,3.963415,NaN

In [164]:
df_sub2_ankle_dribbling = pd.read_csv('..\sensor_data\dribbling_sbj2_ankle.csv', index_col=0)
df_sub2_ankle_dribbling.index = pd.date_range(start='2021-04-14 ' + df_sub2_ankle_dribbling.index[0], periods = df_sub2_ankle_dribbling.shape[0], freq="10.869565ms")
df_sub2_ankle_dribbling = df_sub2_ankle_dribbling.resample('20ms', origin='start').first().interpolate()

df_sub2_ankle_layup = pd.read_csv('..\sensor_data\layup_sbj2_ankle.csv', index_col=0)
df_sub2_ankle_layup.index = pd.date_range(start='2021-04-14 ' + df_sub2_ankle_layup.index[0], periods = df_sub2_ankle_layup.shape[0], freq="10.869565ms")
df_sub2_ankle_layup = df_sub2_ankle_layup.resample('20ms', origin='start').first().interpolate()

df_sub2_ankle_shooting = pd.read_csv('..\sensor_data\shooting_sbj2_ankle_1.csv', index_col=0)
df_sub2_ankle_shooting.index = pd.date_range(start='2021-04-14 ' + df_sub2_ankle_shooting.index[0], periods = df_sub2_ankle_shooting.shape[0], freq="10.869565ms")
df_sub2_ankle_shooting = df_sub2_ankle_shooting.resample('20ms', origin='start').first().interpolate()

df_sub2_ankle_movements = pd.read_csv('..\sensor_data\movements_sbj2_ankle_1.csv', index_col=0)
df_sub2_ankle_movements.index = pd.date_range(start='2021-04-14 ' + df_sub2_ankle_movements.index[0], periods = df_sub2_ankle_movements.shape[0], freq="10.869565ms")
df_sub2_ankle_movements = df_sub2_ankle_movements.resample('20ms', origin='start').first().interpolate()

df_sub2_ankle = pd.concat([df_sub2_ankle_dribbling, df_sub2_ankle_layup, df_sub2_ankle_shooting, df_sub2_ankle_movements])
#df_sub2_ankle.index = pd.date_range(start='2021-04-14 19:26:42.914000', periods = df_sub2_ankle.shape[0], freq="10L")
df_sub2_ankle.sort_index()

                           acc_x    acc_y      acc_z
2021-04-14 18:55:50.361 -0.35400  0.43384  -0.84033;
2021-04-14 18:55:50.381 -0.34399  0.43140  -0.85742;
2021-04-14 18:55:50.401 -0.34741  0.43311  -0.85498;
2021-04-14 18:55:50.421 -0.36670  0.43579  -0.83545;
2021-04-14 18:55:50.441 -0.36646  0.44751  -0.82739;
...                          ...      ...        ...
2021-04-14 19:43:02.121 -0.96143 -0.24438  -0.06689;
2021-04-14 19:43:02.141 -0.96118 -0.23608  -0.06616;
2021-04-14 19:43:02.161 -0.96436 -0.20215  -0.07813;
2021-04-14 19:43:02.181 -0.98047 -0.19702  -0.04956;
2021-04-14 19:43:02.201 -1.00171 -0.17261  -0.08545;

[72999 rows x 3 columns]

In [165]:
df_sub2_wrist_dribbling = pd.read_csv('..\sensor_data\dribbling_sbj2_wrist.csv', index_col=0)
df_sub2_wrist_dribbling.index = pd.date_range(start='2021-04-14 ' + df_sub2_wrist_dribbling.index[0], periods = df_sub2_wrist_dribbling.shape[0], freq="10.869565ms")
df_sub2_wrist_dribbling = df_sub2_wrist_dribbling.resample('20ms', origin='start').first().interpolate()

df_sub2_wrist_layup = pd.read_csv('..\sensor_data\layup_sbj2_wrist.csv', index_col=0)
df_sub2_wrist_layup.index = pd.date_range(start='2021-04-14 ' + df_sub2_wrist_layup.index[0], periods = df_sub2_wrist_layup.shape[0], freq="10.869565ms")
df_sub2_wrist_layup = df_sub2_wrist_layup.resample('20ms', origin='start').first().interpolate()

df_sub2_wrist_shooting = pd.read_csv('..\sensor_data\shooting_sbj2_wrist.csv', index_col=0)
df_sub2_wrist_shooting.index = pd.date_range(start='2021-04-14 ' + df_sub2_wrist_shooting.index[0], periods = df_sub2_wrist_shooting.shape[0], freq="10.869565ms")
df_sub2_wrist_shooting = df_sub2_wrist_shooting.resample('20ms', origin='start').first().interpolate()

df_sub2_wrist_movements = pd.read_csv('..\sensor_data\movements_sbj2_wrist.csv', index_col=0)
df_sub2_wrist_movements.index = pd.date_range(start='2021-04-14 ' + df_sub2_wrist_movements.index[0], periods = df_sub2_wrist_movements.shape[0], freq="10.869565ms")
df_sub2_wrist_movements = df_sub2_wrist_movements.resample('20ms', origin='start').first().interpolate()

df_sub2_wrist = pd.concat([df_sub2_wrist_dribbling, df_sub2_wrist_layup, df_sub2_wrist_shooting, df_sub2_wrist_movements])
#df_sub2_wrist.index = pd.date_range(start='2021-04-14 19:26:24.464000', periods = df_sub2_wrist.shape[0], freq="10L")
df_sub2_wrist.sort_index()

                           acc_x    acc_y      acc_z
2021-04-14 18:56:21.470  0.20972 -0.04395  -0.18628;
2021-04-14 18:56:21.490  0.07617  0.11768  -0.09424;
2021-04-14 18:56:21.510 -0.00098  0.16260   0.18750;
2021-04-14 18:56:21.530  0.04834  0.35522   0.22729;
2021-04-14 18:56:21.550  0.14990  0.42041   0.11694;
...                          ...      ...        ...
2021-04-14 19:42:18.177  0.81201  0.37207  -0.48608;
2021-04-14 19:42:18.197  0.82202  0.39697  -0.50220;
2021-04-14 19:42:18.217  0.83032  0.40356  -0.51953;
2021-04-14 19:42:18.237  0.84497  0.39966  -0.53345;
2021-04-14 19:42:18.257  0.83447  0.32568  -0.40015;

[65292 rows x 3 columns]

In [166]:
df_sub2 = pd.concat([df_sub2_esense, df_sub2_ankle, df_sub2_wrist], axis=1, join="inner")
df_sub2

Empty DataFrame
Columns: [Device, 1, 2, 3, 4, 5, 6, Label, acc_x, acc_y, acc_z, acc_x, acc_y, acc_z]
Index: []