# SUBJECT1

1. Import pandas and numpy libraries.
2. Read the Esense sensor readings csv file into a pandas Dataframe and converting UNIX time to Local TimeZone
3. Upsample Esense data to 100Hz to match with that of Bangle.js Data

In [20]:
import pandas as pd
import numpy as np
df_sub1_esense = pd.read_csv('..\sensor_data\eSense_sbj1.csv', names=['time','Device','E1','E2','E3','E4','E5','E6','Label'], index_col=0)
df_sub1_esense.index = pd.to_datetime(df_sub1_esense.index, unit='ms') + pd.Timedelta('02:00:00')
df_sub1_esense = df_sub1_esense.resample('10ms', origin='start').first().interpolate()
#df_sub1_esense.sort_index()

1. Read Bangle.js ankle sensor readings csv file into pandas Dataframe for each individual activity (of Subject1)
2. Correcting timestamps by keeping the frequency at 92 Hz
3. Upsample Bangle.js data to 100Hz to match with that of Esense Data
4. Merge all activities dataframes into a single dataframe for Ankle sensor

In [21]:
df_sub1_ankle_dribbling = pd.read_csv('..\sensor_data\dribbling_sbj1_ankle.csv', index_col=0)
df_sub1_ankle_dribbling.index = pd.date_range(start='2021-04-14 18:22:13.553', periods = df_sub1_ankle_dribbling.shape[0], freq="10.869565ms")
df_sub1_ankle_dribbling = df_sub1_ankle_dribbling.resample('10ms', origin='start').first().interpolate()

df_sub1_ankle_layup = pd.read_csv('..\sensor_data\layup_sbj1_ankle.csv', index_col=0)
df_sub1_ankle_layup.index = pd.date_range(start='2021-04-14 18:22:13.553', periods = df_sub1_ankle_layup.shape[0], freq="10.869565ms")
df_sub1_ankle_layup = df_sub1_ankle_layup.resample('10ms', origin='start').first().interpolate()

df_sub1_ankle_shooting = pd.read_csv('..\sensor_data\shooting_sbj1_ankle.csv', index_col=0)
df_sub1_ankle_shooting.index = pd.date_range(start='2021-04-14 18:12:54.023', periods = df_sub1_ankle_shooting.shape[0], freq="10.869565ms")
df_sub1_ankle_shooting = df_sub1_ankle_shooting.resample('10ms', origin='start').first().interpolate()

df_sub1_ankle_movements = pd.read_csv('..\sensor_data\movements_sbj1_ankle_1.csv', index_col=0)
df_sub1_ankle_movements.index = pd.date_range(start='2021-04-14 18:42:32.023', periods = df_sub1_ankle_movements.shape[0], freq="10.869565ms")
df_sub1_ankle_movements = df_sub1_ankle_movements.resample('10ms', origin='start').first().interpolate()

df_sub1_ankle = pd.concat([df_sub1_ankle_layup, df_sub1_ankle_shooting, df_sub1_ankle_movements])
df_sub1_ankle['acc_z'] = df_sub1_ankle['acc_z'].replace({';':''}, regex=True)
df_sub1_ankle = df_sub1_ankle.set_axis(['A1', 'A2', 'A3'], axis=1)
df_sub1_ankle['A3'] = df_sub1_ankle['A3'].astype(np.float64)
#df_sub1_ankle.sort_index()

1. Read Bangle.js wrist sensor readings csv file into pandas Dataframe for each individual activity (of Subject1)
2. Correcting timestamps by keeping the frequency at 92 Hz
3. Upsample Bangle.js data to 100Hz to match with that of Esense Data
4. Merge all activities dataframes into a single dataframe for Wrist sensor

In [22]:
df_sub1_wrist_dribbling = pd.read_csv('..\sensor_data\dribbling_sbj1_wrist.csv', index_col=0)
df_sub1_wrist_dribbling.index = pd.date_range(start='2021-04-14 18:32:17.683', periods = df_sub1_wrist_dribbling.shape[0], freq="10.869565ms")
df_sub1_wrist_dribbling = df_sub1_wrist_dribbling.resample('10ms', origin='start').first().interpolate()

df_sub1_wrist_layup = pd.read_csv('..\sensor_data\layup_sbj1_wrist.csv', index_col=0)
df_sub1_wrist_layup.index = pd.date_range(start='2021-04-14 18:22:52.523', periods = df_sub1_wrist_layup.shape[0], freq="10.869565ms")
df_sub1_wrist_layup = df_sub1_wrist_layup.resample('10ms', origin='start').first().interpolate()

df_sub1_wrist_shooting = pd.read_csv('..\sensor_data\shooting_sbj1_wrist.csv', index_col=0)
df_sub1_wrist_shooting.index = pd.date_range(start='2021-04-14 18:13:12.833', periods = df_sub1_wrist_shooting.shape[0], freq="10.869565ms")
df_sub1_wrist_shooting = df_sub1_wrist_shooting.resample('10ms', origin='start').first().interpolate()

df_sub1_wrist_movements = pd.read_csv('..\sensor_data\movements_sbj1_wrist.csv', index_col=0)
df_sub1_wrist_movements.index = pd.date_range(start='2021-04-14 18:42:05.243', periods = df_sub1_wrist_movements.shape[0], freq="10.869565ms")
df_sub1_wrist_movements = df_sub1_wrist_movements.resample('10ms', origin='start').first().interpolate()

df_sub1_wrist = pd.concat([df_sub1_wrist_layup, df_sub1_wrist_shooting, df_sub1_wrist_movements])
df_sub1_wrist['acc_z'] = df_sub1_wrist['acc_z'].replace({';':''}, regex=True)
df_sub1_wrist = df_sub1_wrist.set_axis(['W1', 'W2', 'W3'], axis=1)
df_sub1_wrist['W3'] = df_sub1_wrist['W3'].astype(np.float64)
#df_sub1_wrist.sort_index()

1. Merge Esensor, Ankle, Wrist sensor dataframes into a single dataframe Subject1
2. Relabel all the records as null class
3. Relabel the records into 5 activites as per the Timestamps from the Videos

In [23]:
df_sub1 = pd.concat([df_sub1_esense, df_sub1_ankle, df_sub1_wrist], axis=1, join="inner")
df_sub1.Label = 'null'

#df_sub1.loc[pd.to_datetime('2021-04-14 19:27:01.000'):pd.to_datetime('2021-04-14 19:29:55.000'), 'Label'] = 'dribbling'
df_sub1.loc[pd.to_datetime('2021-04-14 18:23:20.000'):pd.to_datetime('2021-04-14 18:25:25.000'), 'Label'] = 'layup'
df_sub1.loc[pd.to_datetime('2021-04-14 18:45:18.000'):pd.to_datetime('2021-04-14 18:47:11.000'), 'Label'] = 'running'
df_sub1.loc[pd.to_datetime('2021-04-14 18:13:30.000'):pd.to_datetime('2021-04-14 18:15:40.000'), 'Label'] = 'shooting'
df_sub1.loc[pd.to_datetime('2021-04-14 18:42:48.000'):pd.to_datetime('2021-04-14 18:45:17.000'), 'Label'] = 'walking'
#df_sub1

1. Drop unnecessary Columns
2. Drop all rows with any missing values

In [24]:
df_sub1 = df_sub1.drop(columns=['Device'])
df_sub1.dropna(inplace=True)
df_sub1.reset_index(drop=True, inplace=True)
#df_sub1

Normalization
1. Zero mean and Unit Variance standardization

In [31]:
column = ['E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'A1', 'A2', 'A3', 'W1', 'W2', 'W3']
df_sub1[column] = (df_sub1[column] - df_sub1[column].mean()) / df_sub1[column].std()    
df_sub1

,E1,E2,E3,E4,E5,E6,Label,A1,A2,A3,W1,W2,W3
0,0.618401,1.691442,-0.976735,-0.774083,0.433445,0.604095,null,0.107023,0.388318,0.481222,0.669849,-0.174150,0.433733
1,0.617975,1.697821,-0.954008,-0.743713,0.427695,0.626773,null,0.114494,0.376683,0.497912,0.693698,-0.322711,0.356920
2,0.617548,1.704199,-0.931281,-0.713343,0.421946,0.649452,null,0.089287,0.319821,0.550984,0.806475,-0.580197,0.278296
3,0.617121,1.710577,-0.908553,-0.682973,0.416196,0.672131,null,0.055984,0.270973,0.681915,0.800686,-0.686583,0.175765
4,0.616694,1.716956,-0.885826,-0.652603,0.410446,0.694809,null,0.068428,0.298372,0.765344,0.738880,-0.566457,0.123586
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61308,0.811521,1.666805,-1.638273,0.602425,0.129800,-0.919343,null,1.376423,-0.417333,-1.370070,-0.221072,0.241802,-0.366618
61309,0.803810,1.661717,-1.655219,0.583321,0.158357,-0.939325,null,1.350898,-0.414485,-1.445402,-0.219265,0.215291,-0.344150
61310,0.796099,1.656629,-1.672164,0.564217,0.186915,-0.959306,null,1.380465,-0.448088,-1.328615,-0.217459,0.211457,-0.307924
61311,0.642541,1.609496,-1.707376,0.405975,0.348256,-1.115525,null,1.379534,-0.417068,-1.368062,-0.202270,0.229031,-0.281108
61312,0.518489,1.604140,-1.756672,0.348493,0.377943,-1.170020,null,1.359619,-0.382439,-1.441862,-0.194321,0.256183,-0.268063

1. Verify and get Number of records for each activity

In [32]:
df_sub1.loc[df_sub1['Label'] == 'running']

,E1,E2,E3,E4,E5,E6,Label,A1,A2,A3,W1,W2,W3
49219,0.480937,0.072879,0.507433,-0.498172,-0.165455,-0.983526,running,-1.691847,-0.094243,1.208185,0.050730,-1.176338,-0.018435
49220,0.476914,-0.077087,0.619230,-0.648300,-0.541059,-1.277799,running,-1.805156,0.158540,1.491809,0.043861,-1.110531,-0.012276
49221,0.363506,-0.287977,0.753364,-0.731056,-0.603498,-1.468077,running,-1.881107,0.494028,1.623754,0.079272,-1.014678,0.030107
49222,0.335259,-0.309267,0.772180,-0.731310,-0.574295,-1.473073,running,-1.736051,0.994163,1.442257,0.112537,-0.953987,0.048598
49223,0.307012,-0.330557,0.790997,-0.731563,-0.545092,-1.478068,running,-1.248594,1.452173,1.073713,0.146142,-0.886897,0.036993
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58706,2.222908,0.079735,-0.522154,-1.285193,-3.315877,1.371384,running,0.454727,-0.488413,-0.034424,-1.108009,-0.180536,-0.923855
58707,2.297071,0.097730,-0.541696,-1.256858,-3.165636,1.352250,running,0.458463,-0.489705,-0.034424,-1.105833,-0.180863,-0.910083
58708,2.371235,0.115726,-0.561239,-1.228523,-3.015395,1.333116,running,0.459088,-0.489705,-0.027860,-1.102946,-0.185011,-0.894872
58709,-0.378045,-1.277352,1.192299,-1.619396,-1.462642,0.404280,running,0.459088,-0.488922,-0.030387,-1.106203,-0.184056,-0.895599
58710,-0.472124,-1.304881,1.270733,-1.597688,-1.518531,0.479725,running,0.459394,-0.488667,-0.037965,-1.103302,-0.178625,-0.905008