# SUBJECT2

1. Import pandas and numpy libraries.
2. Read the Esense sensor readings csv file into a pandas Dataframe and converting UNIX time to Local TimeZone
3. Upsample Esense data to 100Hz to match with that of Bangle.js Data

In [240]:
import pandas as pd
import numpy as np
df_sub2_esense = pd.read_csv('..\sensor_data\eSense_sbj2.csv', names=['time','Device','E1','E2','E3','E4','E5','E6','Label'], index_col=0)
df_sub2_esense.index = pd.to_datetime(df_sub2_esense.index, unit='ms') + pd.Timedelta('02:00:00')
df_sub2_esense = df_sub2_esense.resample('10ms', origin='start').first().interpolate()
#df_sub2_esense.sort_index()

1. Read Bangle.js ankle sensor readings csv file into pandas Dataframe for each individual activity (of Subject2)
2. Correcting timestamps by keeping the frequency at 92 Hz
3. Upsample Bangle.js data to 100Hz to match with that of Esense Data
4. Merge all activities dataframes into a single dataframe for Ankle sensor

In [241]:
df_sub2_ankle_dribbling = pd.read_csv('..\sensor_data\dribbling_sbj2_ankle.csv', index_col=0)
df_sub2_ankle_dribbling.index = pd.date_range(start='2021-04-14 19:26:42.914', periods = df_sub2_ankle_dribbling.shape[0], freq="10.869565ms")
df_sub2_ankle_dribbling = df_sub2_ankle_dribbling.resample('10ms', origin='start').first().interpolate()

df_sub2_ankle_layup = pd.read_csv('..\sensor_data\layup_sbj2_ankle.csv', index_col=0)
df_sub2_ankle_layup.index = pd.date_range(start='2021-04-14 19:16:25.794', periods = df_sub2_ankle_layup.shape[0], freq="10.869565ms")
df_sub2_ankle_layup = df_sub2_ankle_layup.resample('10ms', origin='start').first().interpolate()

df_sub2_ankle_shooting = pd.read_csv('..\sensor_data\shooting_sbj2_ankle_1.csv', index_col=0)
df_sub2_ankle_shooting.index = pd.date_range(start='2021-04-14 18:55:50.364', periods = df_sub2_ankle_shooting.shape[0], freq="10.869565ms")
df_sub2_ankle_shooting = df_sub2_ankle_shooting.resample('10ms', origin='start').first().interpolate()

df_sub2_ankle_movements = pd.read_csv('..\sensor_data\movements_sbj2_ankle_1.csv', index_col=0)
df_sub2_ankle_movements.index = pd.date_range(start='2021-04-14 19:36:19.244', periods = df_sub2_ankle_movements.shape[0], freq="10.869565ms")
df_sub2_ankle_movements = df_sub2_ankle_movements.resample('10ms', origin='start').first().interpolate()

df_sub2_ankle = pd.concat([df_sub2_ankle_dribbling, df_sub2_ankle_layup, df_sub2_ankle_shooting, df_sub2_ankle_movements])
df_sub2_ankle['acc_z'] = df_sub2_ankle['acc_z'].replace({';':''}, regex=True)
df_sub2_ankle = df_sub2_ankle.set_axis(['A1', 'A2', 'A3'], axis=1)
df_sub2_ankle['A3'] = df_sub2_ankle['A3'].astype(np.float64)
#df_sub2_ankle.sort_index()

1. Read Bangle.js wrist sensor readings csv file into pandas Dataframe for each individual activity (of Subject2)
2. Correcting timestamps by keeping the frequency at 92 Hz
3. Upsample Bangle.js data to 100Hz to match with that of Esense Data
4. Merge all activities dataframes into a single dataframe for Wrist sensor

In [242]:
df_sub2_wrist_dribbling = pd.read_csv('..\sensor_data\dribbling_sbj2_wrist.csv', index_col=0)
df_sub2_wrist_dribbling.index = pd.date_range(start='2021-04-14 19:26:24.464', periods = df_sub2_wrist_dribbling.shape[0], freq="10.869565ms")
df_sub2_wrist_dribbling = df_sub2_wrist_dribbling.resample('10ms', origin='start').first().interpolate()

df_sub2_wrist_layup = pd.read_csv('..\sensor_data\layup_sbj2_wrist.csv', index_col=0)
df_sub2_wrist_layup.index = pd.date_range(start='2021-04-14 19:16:05.604', periods = df_sub2_wrist_layup.shape[0], freq="10.869565ms")
df_sub2_wrist_layup = df_sub2_wrist_layup.resample('10ms', origin='start').first().interpolate()

df_sub2_wrist_shooting = pd.read_csv('..\sensor_data\shooting_sbj2_wrist.csv', index_col=0)
df_sub2_wrist_shooting.index = pd.date_range(start='2021-04-14 18:56:21.474', periods = df_sub2_wrist_shooting.shape[0], freq="10.869565ms")
df_sub2_wrist_shooting = df_sub2_wrist_shooting.resample('10ms', origin='start').first().interpolate()

df_sub2_wrist_movements = pd.read_csv('..\sensor_data\movements_sbj2_wrist.csv', index_col=0)
df_sub2_wrist_movements.index = pd.date_range(start='2021-04-14 19:36:45.074', periods = df_sub2_wrist_movements.shape[0], freq="10.869565ms")
df_sub2_wrist_movements = df_sub2_wrist_movements.resample('10ms', origin='start').first().interpolate()

df_sub2_wrist = pd.concat([df_sub2_wrist_dribbling, df_sub2_wrist_layup, df_sub2_wrist_shooting, df_sub2_wrist_movements])
df_sub2_wrist['acc_z'] = df_sub2_wrist['acc_z'].replace({';':''}, regex=True)
df_sub2_wrist = df_sub2_wrist.set_axis(['W1', 'W2', 'W3'], axis=1)
df_sub2_wrist['W3'] = df_sub2_wrist['W3'].astype(np.float64)
#df_sub2_wrist.sort_index()

1. Merge Esensor, Ankle, Wrist sensor dataframes into a single dataframe Subject2
2. Relabel all the records as null class
3. Relabel the records into 5 activites as per the Timestamps from the Videos

In [243]:
df_sub2 = pd.concat([df_sub2_esense, df_sub2_ankle, df_sub2_wrist], axis=1, join="inner")
df_sub2.Label = 'null'

df_sub2.loc[pd.to_datetime('2021-04-14 19:27:01.000'):pd.to_datetime('2021-04-14 19:29:55.000'), 'Label'] = 'dribbling'
df_sub2.loc[pd.to_datetime('2021-04-14 19:17:40.000'):pd.to_datetime('2021-04-14 19:20:10.000'), 'Label'] = 'layup'
df_sub2.loc[pd.to_datetime('2021-04-14 19:39:47.000'):pd.to_datetime('2021-04-14 19:41:50.000'), 'Label'] = 'running'
df_sub2.loc[pd.to_datetime('2021-04-14 19:00:18.000'):pd.to_datetime('2021-04-14 19:01:42.000'), 'Label'] = 'shooting'
df_sub2.loc[pd.to_datetime('2021-04-14 19:37:18.000'):pd.to_datetime('2021-04-14 19:39:46.000'), 'Label'] = 'walking'
#df_sub2

1. Drop unnecessary Columns
2. Drop all rows with any missing values

In [244]:
df_sub2 = df_sub2.drop(columns=['Device'])
df_sub2.dropna(inplace=True)
df_sub2.reset_index(drop=True, inplace=True)
#df_sub2

Normalization
1. Zero mean and Unit Variance standardization

In [238]:
column = ['E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'A1', 'A2', 'A3', 'W1', 'W2', 'W3']
df_sub2[column] = (df_sub2[column] - df_sub2[column].mean()) / df_sub2[column].std()    
df_sub2

,E1,E2,E3,E4,E5,E6,Label,A1,A2,A3,W1,W2,W3
0,-0.390557,0.235895,-0.152388,0.129028,0.379993,-0.160382,null,0.095712,0.218920,0.078746,-0.227972,-0.513043,1.542037
1,-0.391954,0.236560,-0.156674,0.123981,0.378529,-0.155636,null,0.098784,0.226199,0.075681,-0.222288,-0.444932,1.526225
2,-0.393352,0.237226,-0.160960,0.118934,0.377065,-0.150889,null,0.100328,0.231392,0.081791,-0.236939,-0.417110,1.506633
3,-0.394749,0.237891,-0.165246,0.113887,0.375602,-0.146143,null,0.101084,0.232169,0.087401,-0.256085,-0.403030,1.471984
4,-0.396147,0.238557,-0.169532,0.108840,0.374138,-0.141397,null,0.095712,0.232169,0.114385,-0.277607,-0.393756,1.448257
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75885,-0.158875,1.151302,-2.776552,0.241354,0.291022,-0.113816,null,0.295287,-0.234971,-0.366231,-0.674764,0.558879,0.569187
75886,-0.147549,1.158013,-2.761551,0.260865,0.304502,-0.146412,null,0.303762,-0.234716,-0.373863,-0.669681,0.539690,0.566564
75887,-0.136222,1.164724,-2.746550,0.280376,0.317983,-0.179008,null,0.307605,-0.237057,-0.376407,-0.669387,0.533298,0.561288
75888,-0.124895,1.171435,-2.731549,0.299887,0.331463,-0.211605,null,0.304518,-0.239909,-0.360121,-0.668786,0.531372,0.558264
75889,-0.113569,1.178146,-2.716548,0.319398,0.344943,-0.244201,null,0.302596,-0.240430,-0.367253,-0.665197,0.527862,0.556012

1. Verify and get Number of records for each activity

In [246]:
df_sub2.loc[df_sub2['Label'] == 'walking']

,E1,E2,E3,E4,E5,E6,Label,A1,A2,A3,W1,W2,W3
51429,-0.394586,-0.222385,-0.253174,-230.169377,-141.097561,67.953930,walking,-0.54321,-0.33130,0.92920,0.81885,0.51123,0.87012
51430,-0.362467,-0.212321,-0.249023,-229.837398,-140.182927,67.337398,walking,-0.84766,1.20508,0.04614,0.94360,0.52319,0.87915
51431,-0.330349,-0.202257,-0.244873,-229.505420,-139.268293,66.720867,walking,-0.49658,1.12939,-0.08765,1.05664,0.53906,0.88062
51432,-0.298231,-0.192193,-0.240723,-229.173442,-138.353659,66.104336,walking,-0.57471,0.89624,-0.21948,1.16699,0.57617,0.86572
51433,-0.266113,-0.182129,-0.236572,-228.841463,-137.439024,65.487805,walking,-0.81982,0.42407,-0.01880,1.25903,0.61597,0.85278
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63856,-0.693983,-0.416857,0.183404,-19.441057,-12.327236,-0.328591,walking,-1.20239,-0.00122,-0.67529,0.93604,1.11475,-0.17017
63857,-0.671956,-0.413005,0.172445,-19.847561,-12.408537,-0.294715,walking,-1.62964,0.02075,-0.62866,0.77295,1.00244,-0.19263
63858,-0.660943,-0.411079,0.166965,-20.050813,-12.449187,-0.277778,walking,-1.96924,-0.23047,-0.52368,0.61694,0.91675,-0.20117
63859,-0.649929,-0.409153,0.161485,-20.254065,-12.489837,-0.260840,walking,-2.26294,-0.77222,-0.32837,0.48682,0.84570,-0.19482
63860,-0.638916,-0.407227,0.156006,-20.457317,-12.530488,-0.243902,walking,-2.49927,-1.46777,-0.01685,0.37646,0.79248,-0.18311